### ISSUE TITLE
Critical bugs found in "Creating a custom field type" tutorial

### ISSUE THREAD

**Issue by rtpHarry** [OrchardCMS/OrchardDoc#130]
The tutorial at http://docs.orchardproject.net/Documentation/Creating-a-custom-field-type has several fatal flaws in it which means that it is not possible to create a working module from the tutorial.

It initially looked like the time picker scripts were missing but while looking into this issue for this report it seems that it could have just gone stale as the `Orchard.Jquery` module has entries for `jQueryUI_TimePicker` and `jQueryDateTimeEditor` but the tutorial refers to a non-existent `jQueryUtils_TimePicker`.

* Needs further investigation.
* Source file download will need updating as well.
* csproj needs updating from MVC2 project
* As a courtesy a pull request should be made on the [publicly available module](http://orcharddatetimefield.codeplex.com/) as well
* screenshot in Objectives section shows old admin panel styles

**Comment by jeremygrajales** [comment]
I got this working on 1.9.1 by disabling the Fields feature.
But that is only because it seems that the DateField didn't exist as a core feature when this tutorial was created (not sure). I believe the basis of tutorial is still valid. But maybe another custom field example could be used. Maybe one with simple UI?

**Comment by rtpHarry** [comment]
Yeah, its a bit of a mess at the moment. 

It has been noted in #188 that the documentation needs updating so we should get to it soon :)
