### ISSUE TITLE
Strange very old doc pages on orchardrpoject.net

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/OrchardDoc#283]
For exemple this one
http://docs.orchardproject.net/Documentation/themes-includes

**Comment by rtpHarry** [comment]
Yeah some of the docs are massively out of date but people are thin on the ground that are interested in contributing.

We actually have a project in the works at the moment where we are converting everything over to the "read the docs" platform. It [currently lives here](http://orcharddoc.readthedocs.io/en/mkdocs/) but this has changed several time while we've tried out the various features of the platform so that url might not last.

This will let us set versions up. When it goes live there will be a legacy branch and then a main 1.10 branch. After that I will be a lot more liberal about culling old content.

**Comment by agriffard** [comment]
It was in the archived specs (http://docs.orchardproject.net/Documentation/archived-specs), so it was even before Orchard 1.0.

**Comment by CSurieux** [comment]
I get it searching with search box  from main page ?

**Comment by agriffard** [comment]
Ok, thanks for the precision. With the next version, there will be a breadcrumb and will be more clear that is under the 'archived specs' section.

**Comment by agriffard** [comment]
http://orcharddoc.readthedocs.io/en/mkdocs/Documentation/Themes-includes/
